### ISSUE TITLE
RemoteFhirResource.getResource() does not handle 304 - Not Modified response

### ISSUE THREAD

**Issue by lukeswindale** [AuDigitalHealth/hotspot#3]
### Expected behaviour

* I expected Hotspot to render the requested resource

### Actual behaviour

* I was presented with an error message, stating "Could not sniff format as either JSON or XML.". This is because the server returned a 304 response with an empty body. In this case Hotspot would need to load the cached response but it would appear not to at the moment

### Steps to reproduce

* I think the server was actually incorrectly returning a 304 in this case but I guess it still needs to be handled. Not sure how to force the 304 locally.. however, on the problematic server clicking a link from an external source is enough to trigger it (ie. click a link posted in another application .... perhaps Slack?). The sample link is http://<INTERNAL_SERVER>/fhir/ValueSet/adverse-reaction-agent-1

### Environment

* Problem occurring when opening URL in chrome from external application (implies that you cannot load without looking at the cache). Internal onto sandbox server

**Comment by dionmcm** [comment]
Merged pull request from @lukeswindale who solved this by getting Hotspot to always request the resource again with no cache. This because the response from the server is 304 without setting no cache headers, and that would require the scripting to somehow get the response out of the browser cache.

Getting the content from the browser cache would be preferable reducing unnecessary requests, but it is harder to do.

@johngrimes are you happy with this solution to close this issue, or do you want to pursue the cache access from the scripting?
